server:
  port: 8888
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: provider_route
          uri: http://localhost:9003
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1
#    nacos:
#      discovery:
#        server-addr: 192.168.26.1:8848