server:
  port: 8888
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: provider_route
          uri: http://localhost:9001
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1

