spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.26.1:8848
server:
  port: 9001

provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule