spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.26.1:8848
    sentinel:
      transport:
        dashboard: 192.168.26.1:8080
server:
  port: 9001
management:
  endpoints:
    web:
      exposure:
        include: "*"
rocketmq:
  name-server: 192.168.0.102:9876
  producer:
    group: myprovider
